pool: 'Default'
trigger:
- main

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    repository: 'hema789/spc'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
