---
apiVersion: v1
kind: Pod
metadata:
  name: spc-nop
spec:
  containers:
    - name: springpetclinic
      image: hema789/hello:spc-1.0
      ports:
        - containerPort: 8080
          protocol: "TCP"
    - name: nopcommerce
      image: hema789/hello:nop-2.0
      ports:
        - containerPort: 5000